defaults:
  - _self_
  - action_config: default_action_config
  - slurm: default_slurm
  - aim: default_aim

action_config: ???
debug: ???

# Optional pipeline configuration (only used by pipeline actions)
pipeline_config: {}

run_dir: ".runs/${action_config}/${now:%Y-%m-%d}_${now:%H-%M-%S}"

hydra:
  sweep:
    dir: "${run_dir}_multirun"
